/* export const permissionsList = {
    CREATE: 'CREATE',
    READ: 'READ',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE',
}; */
  
export const permissionsList = {
    CREATE: 'CREATE',
    READ: 'READ',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE',
    CREATE_USER: 'CREATE_USER',
    UPDATE_USER: 'UPDATE_USER',
    READ_USER: 'READ_USER',
    DELETE_USER: 'DELETE_USER',
    CREATE_ROL: 'CREATE_ROL',
    UPDATE_ROL: 'UPDATE_ROL',
    READ_ROL: 'READ_ROL',
    DELETE_ROL: 'DELETE_ROL',
    CREATE_PERMISSION: 'CREATE_PERMISSION',
    UPDATE_PERMISSION: 'UPDATE_PERMISSION',
    READ_PERMISSION: 'READ_PERMISSION',
    DELETE_PERMISSION: 'DELETE_PERMISSION',
    CREATE_CROSS: 'CREATE_CROSS',
    UPDATE_CROSS: 'UPDATE_CROSS',
    READ_CROSS: 'READ_CROSS',
    DELETE_CROSS: 'DELETE_CROSS',
    CREATE_AGV: 'CREATE_AGV',
    UPDATE_AGV: 'UPDATE_AGV',
    READ_AGV: 'READ_AGV',
    DELETE_AGV: 'DELETE_AGV',
};
  