// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

const environment = {
  name: 'prod',
  company: 'prod-tfg-lorenzo',
  production: true,
  hostname: '82.223.202.120', //si no metes la ip del server en prod no pueden acceder desde otro pc que no sea el servidor
  domain: null,
  apiPort: '4100',
  webSocketPort: '8181',
  globalPrefix: 'api',
  apiVersion: 'v1',
  httpsEnabled: false,
  apiUrl: '', // autogenerated
  staticAssetsUrl: '', // autogenerated
  publicFileUrl: '',
  serverSocketUrl: '', // autogenerated
  appPort: '4100', // Angular Frontend Port
};

environment.apiUrl = `${environment.httpsEnabled ? 'https://' : 'http://'}${
  environment.domain && environment.production
    ? environment.domain
    : `${environment.hostname}:${environment.apiPort}`
}/${environment.globalPrefix}/${environment.apiVersion}`;

/* environment.apiUrl = `${environment.httpsEnabled ? 'https://' : 'http://'}${
  environment.domain && environment.production
    ? environment.domain
    : `${environment.hostname}:${environment.apiPort}`
}/${environment.apiVersion}`; */

environment.staticAssetsUrl = `${
  environment.httpsEnabled ? 'https://' : 'http://'
}${
  environment.domain && environment.production
    ? environment.domain
    : `${environment.hostname}:${environment.apiPort}`
}`;

environment.serverSocketUrl = `${
  environment.httpsEnabled ? 'wss://' : 'ws://'
}${
  environment.domain && environment.production
    ? environment.domain
    : `${environment.hostname}:${environment.webSocketPort}`
}`;

environment.publicFileUrl = `${
  environment.httpsEnabled ? 'https://' : 'http://'
}${`${environment.hostname}:
${environment.apiPort}`}/file-uploader-folder`;

export default environment;

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
